version: '3.8'

services:
  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    container_name: admin_service
    ports:
      - "5174:5174"
    environment:
      NODE_ENV: development
    command: ["npm", "run", "dev", "--", "--host", "--port", "5174"]
    networks:
      - app_network

  frontend:
    build:
      context: ./Front End
      dockerfile: Dockerfile
    container_name: frontend_service
    ports:
      - "5173:5173"
    environment:
      NODE_ENV: development
    command: ["npm", "run", "dev", "--", "--host", "--port", "5173"]
    networks:
      - app_network

  backend_primary:
    build:
      context: ./Back End
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
    command: ["node", "index.js"]
    networks:
      - app_network

  backend_replica:
    build:
      context: ./Back End
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
    command: ["node", "index.js"]
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx_service
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend_primary
      - backend_replica
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
